tunnel: c875878d-99ae-4550-9f1b-03bdac260c88
credentials-file: /etc/cloudflared/c875878d-99ae-4550-9f1b-03bdac260c88.json

ingress:
  - hostname: infratrack.solodevmark.com
    service: http://localhost:3001
  - service: http_status:404
